added support for up to 1e177
davidsa03/numerize pull request #5
Opened 2021-11-15 23:21 UTC by kostnerek

I was making game and was needed converter for those clean M, B, T. I found this lib but found out that it supports for up to 'T' so made up my version which supports sufixes up to 1e177

2021-11-16 09:45 UTC, davidsa03 requested changes

2021-11-16 09:45 UTC, davidsa03 commented on numerize/numerize.py
> +def round_num(n):
lets keep the second param `decimals`, so the user can choose how many decimal places they want to show, but have it default to 2 if it is not provided

2021-11-16 09:45 UTC, davidsa03 commented on numerize/test.py
> +class TestNumerizeFunc(unittest.TestCase):
add decimal tests

2021-11-16 14:05 UTC, kostnerek commented
fixed all :)

2021-11-17 01:13 UTC, davidsa03 approved these changes

2021-11-17 01:13 UTC, merged